### ISSUE TITLE
tasks

### ISSUE THREAD

**Issue by rdtarvin** [rdtarvin/IBS2019_Genomics-of-Biodiversity#1]
- [x] decide whether we want to ask participants to do shell lessons in advance, update home page accordingly
- [x] remove questions about computers from [survey](https://www.surveymonkey.com/r/H6NDCHG)
- [x] send out survey, let participants know about the RADseq focus and the fact that they don't need to bring a computer

- [x] are we including any phylogenetics?

- [x] make list of software to install, figure out licenses
- R
- R studio
- fastqc
- stacks & its dependencies
- ??

**Comment by pesalerno** [comment]
I say we do a quick phylogenetics tutorial, with SVDquartets, and a quick R popgen tutorial using adegenet! if there's enough time!! (not sure about that...)

**Comment by rdtarvin** [comment]
Ok, have you done either of those before?
